"""empty message

Revision ID: e4a916cb7f6b
Revises: f51557cbefc5
Create Date: 2016-05-24 17:06:31.461712

"""

# revision identifiers, used by Alembic.
revision = 'e4a916cb7f6b'
down_revision = 'f51557cbefc5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('bio', sa.String(length=120), nullable=True),
    sa.Column('version', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('changed', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'version')
    )
    op.add_column('user', sa.Column('version', sa.Integer(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'version')
    op.drop_table('user_history')
    ### end Alembic commands ###
